"""
Contextual AI — Multi-Feature Demo (Streamlit)
==============================================
Datastores · Agents · RAG queries · PDF parsing · Reranking · GLM · LMUnit Eval.
 
Run locally:
    streamlit run man.py
 
Streamlit Community Cloud:
    Push man.py + requirements.txt to GitHub.
    In Settings → Secrets:
        CONTEXTUAL_API_KEY = "your-key"
"""
 
import os
import io
import json
import base64
from typing import List, Optional, Dict
 
import requests
import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
from dotenv import load_dotenv
 
try:
    from contextual import ContextualAI
except ImportError:
    ContextualAI = None
 
 
# ---------- Page config ----------
st.set_page_config(
    page_title="Contextual AI Demo",
    page_icon="🧠",
    layout="wide",
)
load_dotenv()
 
 
def _clean_key(k: str) -> str:
    """Strip whitespace and any stray surrounding quotes from an API key."""
    if not k:
        return ""
    k = k.strip()
    # remove a single layer of surrounding quotes if present
    if len(k) >= 2 and k[0] == k[-1] and k[0] in ("'", '"'):
        k = k[1:-1].strip()
    return k
 
 
def get_api_key() -> str:
    """Priority: Streamlit secrets → env var → empty. Always cleaned."""
    try:
        if "CONTEXTUAL_API_KEY" in st.secrets:
            return _clean_key(st.secrets["CONTEXTUAL_API_KEY"])
    except Exception:
        pass
    return _clean_key(os.getenv("CONTEXTUAL_API_KEY", ""))
 
 
# ---------- Session state ----------
def init_state():
    defaults = {
        "datastore_id": None,
        "agent_id": None,
        "document_ids": [],
        "last_query_result": None,
        "rerank_with": None,
        "rerank_without": None,
        "rerank_docs": [],
        "rerank_meta": [],
        "parse_job_id": None,
        "parse_result": None,
        "parse_file": None,
        "glm_standard": None,
        "glm_strict": None,
        "glm_irrelevant": None,
        "eval_results": None,
    }
    for k, v in defaults.items():
        st.session_state.setdefault(k, v)
 
init_state()
 
 
# ---------- Constants ----------
BASE_URL = "https://api.contextual.ai/v1"
 
FILES_TO_UPLOAD = [
    ("A_Rev_by_Mkt_Qtrly_Trend_Q425.pdf",
     "https://raw.githubusercontent.com/ContextualAI/examples/refs/heads/main/08-ai-workshop/data/A_Rev_by_Mkt_Qtrly_Trend_Q425.pdf"),
    ("B_Q423-Qtrly-Revenue-by-Market-slide.pdf",
     "https://raw.githubusercontent.com/ContextualAI/examples/refs/heads/main/08-ai-workshop/data/B_Q423-Qtrly-Revenue-by-Market-slide.pdf"),
    ("C_Neptune.pdf",
     "https://raw.githubusercontent.com/ContextualAI/examples/refs/heads/main/08-ai-workshop/data/C_Neptune.pdf"),
    ("D_Unilever.pdf",
     "https://raw.githubusercontent.com/ContextualAI/examples/refs/heads/main/08-ai-workshop/data/D_Unilever.pdf"),
]
 
SYSTEM_PROMPT = """You are a helpful AI assistant created by Contextual AI to answer questions about relevant documentation provided to you. Your responses should be precise, accurate, and sourced exclusively from the provided information. Please follow these guidelines:
* Only use information from the provided documentation. Avoid opinions, speculation, or assumptions.
* Use the exact terminology and descriptions found in the provided content.
* Keep answers concise and relevant to the user's question.
* Use acronyms and abbreviations exactly as they appear in the documentation or query.
* Apply markdown if your response includes lists, tables, or code.
* Directly answer the question, then STOP. Avoid additional explanations unless specifically relevant.
* If the information is irrelevant, simply respond that you don't have relevant documentation and do not provide additional comments or suggestions. Ignore anything that cannot be used to directly answer this query."""
 
SUGGESTED_QUERIES = [
    "What was NVIDIA's annual revenue by fiscal year 2022 to 2025?",
    "When did NVIDIA's data center revenue overtake gaming revenue?",
    "What's the correlation between the distance between Neptune and the Sun and Burglary rates in the US?",
    "What's the correlation between Global revenue generated by Unilever Group and Google searches for 'lost my wallet'?",
    "Does this imply that Unilever Group's revenue is derived from lost wallets?",
    "What's the correlation between the distance between Neptune and the Sun and Global revenue generated by Unilever Group?",
]
 
UNIT_TESTS = [
    "Does the response accurately extract specific numerical data from the documents?",
    "Does the agent properly distinguish between correlation and causation?",
    "Are multi-document comparisons performed correctly with accurate calculations?",
    "Are potential limitations or uncertainties in the data clearly acknowledged?",
    "Are quantitative claims properly supported with specific evidence from the source documents?",
    "Does the response avoid unnecessary information?",
]
 
TEST_CATEGORIES = {
    "Does the response accurately extract specific numerical data": "ACCURACY",
    "Does the agent properly distinguish between correlation and causation": "CAUSATION",
    "Are multi-document comparisons performed correctly": "SYNTHESIS",
    "Are potential limitations or uncertainties in the data": "LIMITATIONS",
    "Are quantitative claims properly supported with specific evidence": "EVIDENCE",
    "Does the response avoid unnecessary information": "RELEVANCE",
}
 
 
# ---------- Sidebar ----------
with st.sidebar:
    st.title("🧠 Contextual AI")
    api_key = st.text_input(
        "API Key",
        type="password",
        value=get_api_key(),
        help="Set CONTEXTUAL_API_KEY in .env or Streamlit Secrets to skip this.",
    )
    api_key = _clean_key(api_key)
    datastore_name = st.text_input("Datastore name", value="Financial_Demo_RAG")
    agent_name = st.text_input("Agent name", value="Demo")
 
    st.divider()
    st.markdown("**State**")
    st.caption(f"Datastore: `{st.session_state.datastore_id or '—'}`")
    st.caption(f"Agent: `{st.session_state.agent_id or '—'}`")
    st.caption(f"Docs ingested: {len(st.session_state.document_ids)}")
 
    # Key sanity check
    if api_key:
        masked = f"{api_key[:4]}…{api_key[-4:]} (len {len(api_key)})"
        st.caption(f"Key: `{masked}`")
        if st.button("🔑 Test API key", use_container_width=True):
            try:
                r = requests.get(
                    f"{BASE_URL}/datastores",
                    headers={"authorization": f"Bearer {api_key}", "accept": "application/json"},
                    timeout=15,
                )
                if r.status_code == 200:
                    st.success("Key is valid ✅")
                else:
                    st.error(f"Status {r.status_code}: {r.text[:200]}")
            except Exception as e:
                st.error(f"Request failed: {e}")
 
    st.divider()
    st.caption("Built with Contextual AI + Streamlit")
 
 
def get_client() -> Optional["ContextualAI"]:
    if ContextualAI is None:
        st.error("`contextual-client` not installed. Run: `pip install contextual-client`")
        return None
    if not api_key:
        st.warning("Please add your Contextual API key in the sidebar.")
        return None
    return ContextualAI(api_key=api_key)
 
 
def map_category(test_q: str) -> Optional[str]:
    for k, v in TEST_CATEGORIES.items():
        if k.lower() in test_q.lower():
            return v
    return None
 
 
# ---------- Header ----------
st.title("🧠 Contextual AI — MANISH SINGH")
st.caption("Datastores · Agents · Parsing · Reranking · GLM · LMUnit Eval")
 
 
# ---------- Tabs ----------
tab_setup, tab_query, tab_parse, tab_rerank, tab_glm, tab_eval = st.tabs(
    ["🏗️ Setup", "💬 Query", "📄 Parse PDF", "🔀 Rerank", "⚡ GLM", "📊 LMUnit"]
)
 
 
# =============================================================
# TAB 1 — SETUP
# =============================================================
with tab_setup:
    st.header("Datastore + Document Ingestion + Agent")
    st.markdown(
        "Run these in order. The demo uses NVIDIA quarterly-revenue PDFs and "
        "two spurious-correlation reports (Neptune, Unilever)."
    )
 
    col1, col2, col3 = st.columns(3)
 
    with col1:
        st.markdown("### 1. Datastore")
        if st.button("Create / Get Datastore", type="primary", use_container_width=True):
            client = get_client()
            if client:
                with st.spinner("Checking datastores..."):
                    try:
                        existing = next(
                            (d for d in client.datastores.list() if d.name == datastore_name),
                            None,
                        )
                        if existing:
                            st.session_state.datastore_id = existing.id
                            st.success(f"Reusing: `{existing.id}`")
                        else:
                            res = client.datastores.create(name=datastore_name)
                            st.session_state.datastore_id = res.id
                            st.success(f"Created: `{res.id}`")
                    except Exception as e:
                        st.error(f"Error: {e}")
 
    with col2:
        st.markdown("### 2. Ingest PDFs")
        if st.button(
            "Download + Ingest Demo PDFs",
            use_container_width=True,
            disabled=not st.session_state.datastore_id,
        ):
            client = get_client()
            if client:
                os.makedirs("data", exist_ok=True)
                doc_ids = []
                progress = st.progress(0.0)
                status = st.empty()
 
                for i, (filename, url) in enumerate(FILES_TO_UPLOAD):
                    fp = f"data/{filename}"
                    status.text(f"Processing {filename}…")
 
                    if not os.path.exists(fp):
                        try:
                            r = requests.get(url, timeout=30)
                            r.raise_for_status()
                            with open(fp, "wb") as f:
                                f.write(r.content)
                        except Exception as e:
                            st.error(f"Download failed for {filename}: {e}")
                            continue
 
                    try:
                        with open(fp, "rb") as f:
                            res = client.datastores.documents.ingest(
                                st.session_state.datastore_id, file=f
                            )
                            doc_ids.append(res.id)
                    except Exception as e:
                        st.error(f"Upload failed for {filename}: {e}")
 
                    progress.progress((i + 1) / len(FILES_TO_UPLOAD))
 
                status.empty()
                progress.empty()
                st.session_state.document_ids = doc_ids
                st.success(f"Ingested {len(doc_ids)} documents.")
 
        if st.session_state.document_ids:
            with st.expander(f"Document IDs ({len(st.session_state.document_ids)})"):
                for d in st.session_state.document_ids:
                    st.code(d, language="text")
 
    with col3:
        st.markdown("### 3. Agent")
        if st.button(
            "Create / Get Agent",
            type="primary",
            use_container_width=True,
            disabled=not st.session_state.datastore_id,
        ):
            client = get_client()
            if client:
                with st.spinner("Setting up agent..."):
                    try:
                        existing = next(
                            (a for a in client.agents.list() if a.name == agent_name),
                            None,
                        )
                        if existing:
                            st.session_state.agent_id = existing.id
                            st.success(f"Reusing: `{existing.id}`")
                        else:
                            resp = client.agents.create(
                                name=agent_name,
                                description="Helpful Grounded AI Assistant",
                                datastore_ids=[st.session_state.datastore_id],
                                agent_configs={
                                    "global_config": {"enable_multi_turn": False}
                                },
                                suggested_queries=SUGGESTED_QUERIES,
                            )
                            st.session_state.agent_id = resp.id
                            st.success(f"Created: `{resp.id}`")
                    except Exception as e:
                        st.error(f"Error: {e}")
 
    st.divider()
 
    with st.expander("📋 System prompt"):
        st.code(SYSTEM_PROMPT, language="markdown")
    with st.expander("💡 Suggested queries"):
        for q in SUGGESTED_QUERIES:
            st.markdown(f"- {q}")
 
    if st.session_state.document_ids and st.button("🔍 Inspect first doc metadata"):
        client = get_client()
        if client:
            try:
                meta = client.datastores.documents.metadata(
                    datastore_id=st.session_state.datastore_id,
                    document_id=st.session_state.document_ids[0],
                )
                st.json(meta if isinstance(meta, dict) else getattr(meta, "model_dump", lambda: meta)())
            except Exception as e:
                st.error(f"Error: {e}")
 
 
# =============================================================
# TAB 2 — QUERY AGENT
# =============================================================
with tab_query:
    st.header("Query the RAG Agent")
 
    if not st.session_state.agent_id:
        st.warning("Create the agent first (Setup tab).")
    else:
        preset = st.selectbox("Preset queries", ["—"] + SUGGESTED_QUERIES, index=0)
        default_q = preset if preset != "—" else "What was NVIDIA's annual revenue by fiscal year 2022 to 2025?"
 
        query_text = st.text_area("Your question", value=default_q, height=80)
 
        if st.button("🔍 Query", type="primary"):
            client = get_client()
            if client and query_text.strip():
                with st.spinner("Querying agent..."):
                    try:
                        result = client.agents.query.create(
                            agent_id=st.session_state.agent_id,
                            messages=[{"content": query_text, "role": "user"}],
                        )
                        st.session_state.last_query_result = result
                    except Exception as e:
                        st.error(f"Query failed: {e}")
 
        if st.session_state.last_query_result:
            result = st.session_state.last_query_result
 
            st.subheader("📝 Answer")
            st.markdown(result.message.content)
 
            if result.retrieval_contents:
                st.subheader(f"📚 Retrieved Documents ({len(result.retrieval_contents)})")
                client = get_client()
                if client:
                    cols = st.columns(min(2, len(result.retrieval_contents)))
                    for i, rc in enumerate(result.retrieval_contents):
                        with cols[i % len(cols)]:
                            st.markdown(f"**Document {i + 1}**")
                            try:
                                ret = client.agents.query.retrieval_info(
                                    message_id=result.message_id,
                                    agent_id=st.session_state.agent_id,
                                    content_ids=[rc.content_id],
                                )
                                if ret.content_metadatas and ret.content_metadatas[0].page_img:
                                    img_data = base64.b64decode(ret.content_metadatas[0].page_img)
                                    img = Image.open(io.BytesIO(img_data))
                                    st.image(img, use_column_width=True)
                                else:
                                    st.caption("No image preview available.")
                            except Exception as e:
                                st.caption(f"Couldn't load preview: {e}")
 
 
# =============================================================
# TAB 3 — PARSE PDF
# =============================================================
with tab_parse:
    st.header("Parse a PDF")
    st.markdown("Submit a PDF for structured parsing (markdown-per-page output).")
 
    src = st.radio(
        "Source",
        ["Demo (Attention Is All You Need)", "Upload your own"],
        horizontal=True,
    )
 
    if src == "Demo (Attention Is All You Need)":
        if st.button("⬇️ Use demo paper"):
            os.makedirs("data", exist_ok=True)
            fp = "data/attention-is-all-you-need.pdf"
            if not os.path.exists(fp):
                with st.spinner("Downloading paper..."):
                    try:
                        r = requests.get("https://arxiv.org/pdf/1706.03762", timeout=30)
                        with open(fp, "wb") as f:
                            f.write(r.content)
                    except Exception as e:
                        st.error(f"Download failed: {e}")
                        fp = None
            if fp:
                st.session_state.parse_file = fp
                st.success(f"Ready: `{fp}`")
    else:
        upload = st.file_uploader("Upload PDF", type=["pdf"])
        if upload:
            os.makedirs("data", exist_ok=True)
            fp = f"data/{upload.name}"
            with open(fp, "wb") as f:
                f.write(upload.getbuffer())
            st.session_state.parse_file = fp
            st.success(f"Saved: `{fp}`")
 
    if st.session_state.parse_file:
        st.info(f"Active file: `{st.session_state.parse_file}`")
 
    page_range = st.text_input("Page range", value="0-5",
                               help="Format: 'start-end' (zero-indexed). e.g. '0-5' = first 6 pages.")
    c1, c2, c3 = st.columns(3)
    with c1:
        parse_mode = st.selectbox("Parse mode", ["standard"], index=0)
    with c2:
        figure_mode = st.selectbox("Figure caption", ["concise", "detailed", "off"], index=0)
    with c3:
        hierarchy = st.checkbox("Doc hierarchy", value=True)
 
    if st.button(
        "🚀 Submit Parse Job",
        type="primary",
        disabled=not (st.session_state.parse_file and api_key),
    ):
        url = f"{BASE_URL}/parse"
        headers = {"accept": "application/json", "authorization": f"Bearer {api_key}"}
        config = {
            "parse_mode": parse_mode,
            "figure_caption_mode": figure_mode,
            "enable_document_hierarchy": hierarchy,
            "page_range": page_range,
        }
        try:
            with st.spinner("Submitting..."):
                with open(st.session_state.parse_file, "rb") as fp:
                    files = {"raw_file": fp}
                    r = requests.post(url, headers=headers, data=config, files=files, timeout=60)
                    resp = r.json()
            jid = resp.get("job_id")
            if jid:
                st.session_state.parse_job_id = jid
                st.session_state.parse_result = None
                st.success(f"Job submitted: `{jid}`")
            else:
                st.error(f"Unexpected response: {resp}")
        except Exception as e:
            st.error(f"Submission failed: {e}")
 
    if st.session_state.parse_job_id:
        st.markdown(f"**Active job:** `{st.session_state.parse_job_id}`")
        if st.button("📥 Fetch Results"):
            url = f"{BASE_URL}/parse/jobs/{st.session_state.parse_job_id}/results"
            headers = {"accept": "application/json", "authorization": f"Bearer {api_key}"}
            try:
                with st.spinner("Fetching..."):
                    r = requests.get(
                        url, headers=headers,
                        params={"output_types": "markdown-per-page"}, timeout=30,
                    )
                    st.session_state.parse_result = r.json()
            except Exception as e:
                st.error(f"Fetch failed: {e}")
 
    if st.session_state.parse_result:
        res = st.session_state.parse_result
        st.metric("Status", res.get("status", "unknown"))
        pages = res.get("pages", [])
        if pages:
            page_idx = st.slider("Page", 0, len(pages) - 1, 0)
            st.markdown(pages[page_idx].get("markdown", "_(empty page)_"))
        else:
            st.warning("No parsed pages yet — job may still be processing. Try fetching again.")
 
 
# =============================================================
# TAB 4 — RERANK
# =============================================================
with tab_rerank:
    st.header("Reranker — With vs Without Instruction")
    st.markdown(
        "Compare how `ctxl-rerank-en-v1-instruct` ranks the same documents "
        "when given an instruction vs not."
    )
 
    query_r = st.text_area(
        "Query",
        value="What is the current enterprise pricing for the RTX 5090 GPU for bulk orders?",
        height=70,
    )
    instruction_r = st.text_area(
        "Instruction",
        value=("Prioritize internal sales documents over market analysis reports. "
               "More recent documents should be weighted higher. Enterprise portal "
               "content supersedes distributor communications."),
        height=80,
    )
 
    default_docs = [
        ("Following detailed cost analysis and market research, we have implemented the following changes: "
         "AI training clusters will see a 15% uplift in raw compute performance, enterprise support packages "
         "are being restructured, and bulk procurement programs (100+ units) for the RTX 5090 Enterprise series "
         "will operate on a $2,899 baseline."),
        ("Enterprise pricing for the RTX 5090 GPU bulk orders (100+ units) is currently set at $3,100-$3,300 "
         "per unit. This pricing for RTX 5090 enterprise bulk orders has been confirmed across all major "
         "distribution channels."),
        "RTX 5090 Enterprise GPU requires 450W TDP and 20% cooling overhead.",
    ]
    default_meta = [
        "Date: January 15, 2025. Source: NVIDIA Enterprise Sales Portal. Classification: Internal Use Only",
        "TechAnalytics Research Group. 11/30/2023.",
        "January 25, 2025; NVIDIA Enterprise Sales Portal; Internal Use Only",
    ]
 
    docs_input = st.text_area("Documents (one per line)", value="\n".join(default_docs), height=160)
    meta_input = st.text_area("Metadata (one per line, same order)",
                              value="\n".join(default_meta), height=120)
 
    if st.button("🔀 Run Rerank Comparison", type="primary"):
        client = get_client()
        if client:
            documents = [d.strip() for d in docs_input.split("\n") if d.strip()]
            metadata_list = [m.strip() for m in meta_input.split("\n") if m.strip()]
 
            if len(documents) != len(metadata_list):
                st.error("Documents and metadata line counts must match.")
            else:
                model = "ctxl-rerank-en-v1-instruct"
                try:
                    with st.spinner("Reranking (with + without instruction)..."):
                        with_res = client.rerank.create(
                            query=query_r, instruction=instruction_r,
                            documents=documents, metadata=metadata_list, model=model,
                        )
                        without_res = client.rerank.create(
                            query=query_r, documents=documents,
                            metadata=metadata_list, model=model,
                        )
                    st.session_state.rerank_with = with_res
                    st.session_state.rerank_without = without_res
                    st.session_state.rerank_docs = documents
                    st.session_state.rerank_meta = metadata_list
                except Exception as e:
                    st.error(f"Rerank failed: {e}")
 
    if st.session_state.rerank_with and st.session_state.rerank_without:
        docs = st.session_state.rerank_docs
        meta = st.session_state.rerank_meta
 
        c1, c2 = st.columns(2)
        with c1:
            st.subheader("Without instruction")
            for i, r in enumerate(st.session_state.rerank_without.results):
                with st.container(border=True):
                    st.markdown(f"**Rank {i+1}** · Doc {r.index + 1} · Score `{r.relevance_score:.4f}`")
                    st.caption(meta[r.index])
                    txt = docs[r.index]
                    st.write(txt[:220] + ("…" if len(txt) > 220 else ""))
        with c2:
            st.subheader("With instruction")
            for i, r in enumerate(st.session_state.rerank_with.results):
                with st.container(border=True):
                    st.markdown(f"**Rank {i+1}** · Doc {r.index + 1} · Score `{r.relevance_score:.4f}`")
                    st.caption(meta[r.index])
                    txt = docs[r.index]
                    st.write(txt[:220] + ("…" if len(txt) > 220 else ""))
 
 
# =============================================================
# TAB 5 — GLM
# =============================================================
with tab_glm:
    st.header("Grounded Language Model (GLM)")
    st.markdown("Generate responses strictly grounded in provided knowledge sources.")
 
    DEFAULT_MESSAGES = [
        {"role": "user",
         "content": "What are the most promising renewable energy technologies for addressing climate change in developing nations?"},
        {"role": "assistant",
         "content": ("Based on current research, solar and wind power show significant potential for "
                     "developing nations due to decreasing costs and scalability. Would you like to know more "
                     "about specific implementation challenges and success stories?")},
        {"role": "user",
         "content": "Yes, please tell me about successful solar implementations in Africa and their economic impact, particularly focusing on rural electrification."},
    ]
 
    DEFAULT_KNOWLEDGE = [
        ("According to the International Renewable Energy Agency (IRENA) 2023 report:\n"
         "- Solar PV installations in Africa reached 10.4 GW in 2022\n"
         "- The cost of solar PV modules decreased by 80% between 2010 and 2022\n"
         "- Rural electrification projects have provided power to 17 million households"),
        ("Case Study: Rural Electrification in Kenya (2020-2023)\n"
         "- 2.5 million households connected through mini-grid systems\n"
         "- Average household income increased by 35% after electrification\n"
         "- Local businesses reported 47% growth in revenue\n"
         "- Education outcomes improved with 3 additional study hours per day"),
        ("Economic Analysis of Solar Projects in Sub-Saharan Africa:\n"
         "- Job creation: 25 jobs per MW of installed capacity\n"
         "- ROI average of 12-15% for mini-grid projects\n"
         "- Reduced energy costs by 60% compared to diesel generators\n"
         "- Carbon emissions reduction: 2.3 million tonnes CO2 equivalent"),
        ("Technical Specifications and Best Practices:\n"
         "- Optimal solar panel efficiency in African climate conditions: 15-22%\n"
         "- Battery storage requirements: 4-8 kWh per household\n"
         "- Maintenance costs: $0.02-0.04 per kWh\n"
         "- Expected system lifetime: 20-25 years"),
        ("Social Impact Assessment:\n"
         "- Women-led businesses increased by 45% in electrified areas\n"
         "- Healthcare facilities reported 72% improvement in service delivery\n"
         "- Mobile money usage increased by 60%\n"
         "- Agricultural productivity improved by 28% with electric irrigation"),
    ]
 
    with st.expander("📜 Conversation messages (JSON)", expanded=False):
        messages_str = st.text_area(
            "Messages",
            value=json.dumps(DEFAULT_MESSAGES, indent=2),
            height=240,
            label_visibility="collapsed",
        )
 
    with st.expander("📚 Knowledge sources (separate with `---`)", expanded=False):
        knowledge_str = st.text_area(
            "Knowledge",
            value="\n\n---\n\n".join(DEFAULT_KNOWLEDGE),
            height=300,
            label_visibility="collapsed",
        )
 
    c1, c2, c3 = st.columns(3)
    with c1:
        temperature = st.slider("Temperature", 0.0, 1.0, 0.0, 0.1)
    with c2:
        top_p = st.slider("Top-p", 0.0, 1.0, 0.9, 0.05)
    with c3:
        max_tokens = st.number_input("Max tokens", 64, 4096, 1024, 64)
 
    if st.button("⚡ Generate (Standard + Strict)", type="primary"):
        if not api_key:
            st.error("API key required.")
        else:
            try:
                messages = json.loads(messages_str)
                knowledge = [k.strip() for k in knowledge_str.split("---") if k.strip()]
            except Exception as e:
                st.error(f"Invalid messages JSON: {e}")
                messages = knowledge = None
 
            if messages and knowledge:
                url = f"{BASE_URL}/generate"
                headers = {
                    "accept": "application/json",
                    "content-type": "application/json",
                    "authorization": f"Bearer {api_key}",
                }
                base_payload = {
                    "model": "v1",
                    "messages": messages,
                    "knowledge": knowledge,
                    "max_new_tokens": int(max_tokens),
                    "temperature": float(temperature),
                    "top_p": float(top_p),
                }
                try:
                    with st.spinner("Generating both modes..."):
                        r1 = requests.post(url, json={**base_payload, "avoid_commentary": False},
                                           headers=headers, timeout=60)
                        st.session_state.glm_standard = r1.json().get("response", str(r1.json()))
                        r2 = requests.post(url, json={**base_payload, "avoid_commentary": True},
                                           headers=headers, timeout=60)
                        st.session_state.glm_strict = r2.json().get("response", str(r2.json()))
                except Exception as e:
                    st.error(f"GLM error: {e}")
 
    if st.session_state.glm_standard:
        c1, c2 = st.columns(2)
        with c1:
            st.subheader("Standard (`avoid_commentary=False`)")
            st.markdown(st.session_state.glm_standard)
        with c2:
            st.subheader("Strict (`avoid_commentary=True`)")
            st.markdown(st.session_state.glm_strict or "_(no response)_")
 
    st.divider()
    st.subheader("Grounding sanity check — irrelevant query")
    st.caption("Send an off-topic question with the same renewable-energy knowledge. "
               "A well-grounded model should refuse to answer.")
    if st.button("🧪 Test irrelevant query"):
        if not api_key:
            st.error("API key required.")
        else:
            url = f"{BASE_URL}/generate"
            headers = {
                "accept": "application/json",
                "content-type": "application/json",
                "authorization": f"Bearer {api_key}",
            }
            try:
                knowledge = [k.strip() for k in knowledge_str.split("---") if k.strip()]
            except Exception:
                knowledge = DEFAULT_KNOWLEDGE
            payload = {
                "model": "v1",
                "messages": [{"role": "user",
                              "content": "What are the latest developments in quantum computing hardware?"}],
                "knowledge": knowledge,
                "avoid_commentary": False,
                "max_new_tokens": 512,
                "temperature": 0,
                "top_p": 0.9,
            }
            try:
                with st.spinner("Generating..."):
                    r = requests.post(url, json=payload, headers=headers, timeout=60)
                    st.session_state.glm_irrelevant = r.json().get("response", str(r.json()))
            except Exception as e:
                st.error(f"GLM error: {e}")
 
    if st.session_state.glm_irrelevant:
        st.info("**Query:** What are the latest developments in quantum computing hardware?  \n"
                "**Knowledge:** renewable-energy data (irrelevant)")
        st.markdown(st.session_state.glm_irrelevant)
 
 
# =============================================================
# TAB 6 — LMUNIT EVAL
# =============================================================
with tab_eval:
    st.header("LMUnit — Response Evaluation")
    st.markdown("Evaluate responses across 6 dimensions. Edit the table to add your own prompts/responses.")
 
    DEFAULT_EVAL = [
        {"prompt": "What was NVIDIA's Data Center revenue in Q4 FY25?",
         "response": ("NVIDIA's Data Center revenue for Q4 FY25 was $35,580 million. "
                      "This represents a significant increase from the previous quarter.")},
        {"prompt": "What is the correlation coefficient between Neptune's distance from the Sun and US burglary rates?",
         "response": ("According to the Tyler Vigen spurious correlations dataset, there is a correlation "
                      "coefficient of 0.87 between Neptune's distance from the Sun and US burglary rates. "
                      "However, this is clearly a spurious correlation with no causal relationship.")},
        {"prompt": "How did NVIDIA's total revenue change from Q1 FY22 to Q4 FY25?",
         "response": ("NVIDIA's total revenue grew from $5.66 billion in Q1 FY22 to $60.9 billion in Q4 FY25, "
                      "representing a massive increase driven primarily by AI and data center demand.")},
    ]
 
    eval_df = pd.DataFrame(DEFAULT_EVAL)
    edited_df = st.data_editor(
        eval_df,
        num_rows="dynamic",
        use_container_width=True,
        column_config={
            "prompt": st.column_config.TextColumn("Prompt", width="medium"),
            "response": st.column_config.TextColumn("Response", width="large"),
        },
    )
 
    with st.expander("Unit tests being run"):
        for t in UNIT_TESTS:
            st.markdown(f"- {t}")
 
    if st.button("📊 Run Evaluation", type="primary"):
        client = get_client()
        if client:
            results = []
            total = max(1, len(edited_df) * len(UNIT_TESTS))
            done = 0
            progress = st.progress(0.0)
 
            for _, row in edited_df.iterrows():
                if not row.get("prompt") or not row.get("response"):
                    continue
                row_results = []
                for test in UNIT_TESTS:
                    try:
                        r = client.lmunit.create(
                            query=row["prompt"], response=row["response"], unit_test=test
                        )
                        row_results.append({"test": test, "score": r.score})
                    except Exception as e:
                        row_results.append({"test": test, "score": None, "error": str(e)})
                    done += 1
                    progress.progress(min(done / total, 1.0))
                results.append({
                    "prompt": row["prompt"],
                    "response": row["response"],
                    "test_results": row_results,
                })
            progress.empty()
            st.session_state.eval_results = results
            st.success(f"Evaluated {len(results)} responses × {len(UNIT_TESTS)} tests.")
 
    if st.session_state.eval_results:
        results = st.session_state.eval_results
 
        # Aggregate
        all_scores = []
        for r in results:
            for tr in r["test_results"]:
                if tr.get("score") is not None:
                    all_scores.append({
                        "category": map_category(tr["test"]),
                        "score": tr["score"],
                    })
        scores_df = pd.DataFrame(all_scores)
 
        if not scores_df.empty:
            st.subheader("Aggregate by category")
            agg = scores_df.groupby("category")["score"].agg(["mean", "std", "count"]).round(2)
            st.dataframe(agg, use_container_width=True)
            c1, c2, c3 = st.columns(3)
            c1.metric("Mean", f"{scores_df['score'].mean():.2f} / 5")
            c2.metric("Std", f"{scores_df['score'].std():.2f}")
            c3.metric("N", len(scores_df))
 
        # Radar plots
        st.subheader("Per-evaluation radar plots")
        categories = ["ACCURACY", "CAUSATION", "SYNTHESIS", "LIMITATIONS", "EVIDENCE", "RELEVANCE"]
        angles = np.linspace(0, 2 * np.pi, len(categories), endpoint=False)
        angles = np.concatenate((angles, [angles[0]]))
 
        n = len(results)
        if n > 0:
            fig = plt.figure(figsize=(6 * n, 6))
            for plot_idx, result in enumerate(results):
                ax = plt.subplot(1, n, plot_idx + 1, projection="polar")
                scores = []
                for cat in categories:
                    score = None
                    for tr in result["test_results"]:
                        if map_category(tr["test"]) == cat:
                            score = tr.get("score")
                            break
                    scores.append(score if score is not None else 0)
                scores = np.concatenate((scores, [scores[0]]))
                ax.plot(angles, scores, "o-", linewidth=2, color="#4f46e5")
                ax.fill(angles, scores, alpha=0.25, color="#4f46e5")
                ax.set_xticks(angles[:-1])
                ax.set_xticklabels(categories, fontsize=9)
                ax.set_ylim(0, 5)
                ax.grid(True)
                for a, s in zip(angles[:-1], scores[:-1]):
                    ax.text(a, s + 0.2, f"{s:.1f}", ha="center", va="bottom", fontsize=8)
                title = result["prompt"][:50] + ("…" if len(result["prompt"]) > 50 else "")
                ax.set_title(f"Eval {plot_idx + 1}\n{title}", pad=20, fontsize=10)
            plt.tight_layout()
            st.pyplot(fig)
 
        with st.expander("Raw results"):
            for i, r in enumerate(results):
                st.markdown(f"### Eval {i+1}")
                st.markdown(f"**Prompt:** {r['prompt']}")
                st.markdown(f"**Response:** {r['response']}")
                for tr in r["test_results"]:
                    cat = map_category(tr["test"]) or "OTHER"
                    score = tr.get("score")
                    if score is not None:
                        st.markdown(f"- **{cat}**: {score:.2f}/5")
                    else:
                        st.markdown(f"- **{cat}**: error — {tr.get('error', 'unknown')}")
 
 
# ---------- Footer ----------
st.divider()
with st.expander("📦 requirements.txt"):
    st.code(
        "streamlit>=1.32\n"
        "contextual-client>=0.6\n"
        "pandas>=2.0\n"
        "numpy>=1.24\n"
        "matplotlib>=3.7\n"
        "Pillow>=10.0\n"
        "requests>=2.31\n"
        "python-dotenv>=1.0\n",
        language="text",
    )
